server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
    password: nD5kaJMWRRV2vVlT
    username: postgres.awqjcwicvpsisinrmeap
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 3
